version: "3"
services:
  ubuntuplus:
    container_name: ubuntuplus
    image: anotherlittlecat/ubuntuplus
    ports:
      - "23:22"
    hostname: "dev-docker"
    stdin_open: true
    tty: true
    volumes:
      - .ssh:/home/user/.ssh
      - .zshrc:/home/user/.zshrc
      - .zsh_history:/home/user/.zsh_history
      - .tldr:/home/user/.tldr
      - .vscode-server:/home/user/.vscode-server
      - .gitconfig:/home/user/.gitconfig
      - ../../project:/home/user/code
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - UMASK_SET=<022> #optional
